defaults:
  - dataset: mov_mnist
#  - dataset: boun_balls
#  - dataset: dsprites

#resume: '/home/acomasma/ool-dynamics/dk/outputs/test_circle/Koopman_Disentanglement/models/checkpoint-epoch1.pth'
resume:
device:
run_id: