defaults:
  - dataset: mov_mnist
#  - dataset: dsprites

#resume: '/home/acomasma/ool-dynamics/deep-koopman/outputs/test_4/Koopman_Disentanglement/models/checkpoint-epoch3.pth'
resume:
device:
run_id: