name: "Koopman_Disentanglement"
n_gpu: 1

#TODO: Ask haolin to change step size to 0.3
# Global variables
n_timesteps: &NTS 3 # Number of timesteps seen in each state. Time length of the state
image_size: &IS [128, 128] # Input image size
seq_length: &SeqL 13 # Length of the observed sequence.
n_objects: &Nobj 3

log_step: 50

loss: "embedding_loss"
#loss: "explicit_embedding_loss"


data_loader:
  type: "MovingMNISTLoader"
  args:
    dataset_case: "constant_vel"
    dataset_name: ""
    seq_length: *SeqL
    seq_stride: 1
    image_size: 128
    n_objects: *Nobj
    data_dir: "/home/acomasma/ool-dynamics/deep-koopman/data"
    batch_size: &BS 40
    shuffle: true
    training_split: 0.9
    validation_split: 0.1
    dataset_reduction: 0.0 #0.94
    num_workers: 2
    training: True

# TODO: probar betas=(0.5, 0.999))
arch:
  type: "RecKoopmanModel"
  args:
    in_channels: 1
    feat_dim: &Fdim 50
    g_dim: &Gdim 15
    r_dim: 10
    u_dim: 4 # 15, 4
    n_objects: *Nobj
    I_factor: 1
    n_blocks: 1
    nf_particle: &Hdim 40
    nf_effect: *Hdim
    psteps: 1
    n_timesteps: *NTS
    ngf: 8
    image_size: *IS
    free_pred: 15
    with_interactions: False
    with_u: True
    batch_size: *BS
    cte_app: True
#    collision_margin: 0.3

optimizer:
  type: "Adam"
  args:
    lr: 5e-4
    betas: [0.9, 0.999]
    weight_decay: 0.0001
    amsgrad: true

metrics: [] #["accuracy", "top_k_acc"]

#lr_scheduler:
#  type: "StepLR"
#  args:
#    step_size: 20
#    gamma: 0.3

lr_scheduler:
  type: "ReduceLROnPlateau"
  args:
    mode: 'min'
    factor: 0.4
    patience: 4
    verbose: True

trainer:
  epochs: 300
  save_dir: ""
  save_period: 1
  verbosity: 2
  monitor: "min val_loss"
  early_stop: 100
  tensorboard: true
  lambd: 0.0